
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Pomodoro Timer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" dark">
      <head>
      <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
            rel="stylesheet"
        />
      </head>
      <body 
        className={` font-sans antialiased dark:text-text-primary text-text-accent `}
      >
        {children}
      </body>
    </html>
  );
}
